# Data Documentation

The dataset can be found here: [Kaggle College Basketball Dataset](https://www.kaggle.com/datasets/andrewsundberg/college-basketball-dataset).

[**First 10 Rows of CBB Dataset:**]{.underline}

```{r}
#| echo: FALSE
#| warning: FALSE
#| label: tbl-cbb
#| tbl-cap: "College Basketball Defensive Data for NCAA Basketball Seasons from 2013-2025"
#| results: asis

cbb <- read.csv("cbb.csv")

writeLines("\\footnotesize")
knitr::kable(head(cbb[c(1:4,6:7,9,22:24)], 10))
writeLines("\\normalsize")

```

[**Variable List:**]{.underline}

```{r}
#| echo: FALSE
#| warning: FALSE
#| label: tbl-var
#| tbl-cap: "Dataset Variable Names and Descriptions"
#| results: asis

cbb.variables <- data.frame(Variable=c("TEAM", "CONF", "W", "ADJDE", "BARTHAG", 
                                       "POSTSEASON", "SEED", "YEAR"),
                        Description=c("NCAA Division I School Name",
                                      "Athletic Conference", 
                                      "Games Won", 
                                      "Adjusted Defensive Efficiency (Pts Allowed/100 Poss.)",
                                      "Power Rating (Win % vs avg DI team)",
                                      "Tournament Exit Round (e.g., S16, F4, Champion)",
                                      "Tournament Seed", "Season Year"))

writeLines("\\footnotesize")
knitr::kable(cbb.variables)
writeLines("\\normalsize")

```
